info_to_extract = [
    "periodo_di_retribuzione (è una stringa ed è mandatory)",
    "totale_retribuzione_minima_lorda (è un int ed è la somma di Paga Base, Conting, 3Elemen e Sup. ass.) è mandatory",
    "giorni_lavorati (è un double e non sono mandatory)",
    "ore_lavorate (è un double e non sono mandatory)",
    "ore_straordinarie (è un double e non sono mandatory)",
    "ritenute_irpef (è un double ed è mandatory)",
    "totale_competenze (è un double ed è mandatory)",
    "totale_trattenute (è un double ed è mandatory)",
    "arrotondamento (è un double ed è mandatory)",
    "netto_del_mese (è un double ed è mandatory)",
    "retribuzione_utile_tfr (è un double ed è mandatory)",
    "quota_tfr (è un double ed è mandatory)",
    "ferie_giorni_residuo_anno_precedente (è un double ed è mandatory)",
    "permessi_ore_residuo_anno_precedente (è un double ed è mandatory)",
    "ferie_giorni_spettante (è un double ed è mandatory)",
    "permessi_ore_spettante (è un double ed è mandatory)",
    "totale_ferie_rimanenti (è un double ed è mandatory)",
    "totale_permessi_rimanenti (è un double ed è mandatory)"
]

mandatory_fields = [
    "periodo_di_retribuzione",
    "totale_retribuzione_minima_lorda",
    "ritenute_irpef",
    "totale_competenze",
    "totale_trattenute",
    "arrotondamento",
    "netto_del_mese",
    "retribuzione_utile_tfr",
    "quota_tfr",
    "ferie_giorni_residuo_anno_precedente",
    "permessi_ore_residuo_anno_precedente",
    "ferie_giorni_spettante",
    "permessi_ore_spettante",
    "totale_ferie_rimanenti",
    "totale_permessi_rimanenti"
]

columns_to_select = [
    "ragione_sociale_azienda",
    "date_periodo_di_retribuzione",
    "string_periodo_di_retribuzione",
    "retribuzione_minima_lorda",
    "giorni_lavorati",
    "ore_lavorate",
    "percentuale_maggiorazione_ore_straordinario",
    "ore_straordinarie",
    "irpef_pagata",
    "totale_competenze",
    "totale_trattenute",
    "arrotondamento",
    "netto_del_mese",
    "retribuzione_utile_tfr",
    "quota_tfr",
    "ferie_giorni_residuo_anno_precedente",
    "permessi_ore_residuo_anno_precedente",
    "ferie_giorni_spettante",
    "permessi_ore_spettante",
    "totale_ferie_rimanenti",
    "totale_permessi_rimanenti",
    "note"
]
